### PR TITLE
Add vue 3 compatibility

### PR DESCRIPTION
**Pull request by semanticmx**
Upgraded module for Vue 3.

vue-3

## what

* Updated checkout component to support vue3
* Updated StripeElementCard to support vue3
* Updated Stripe plugin to support vue3

## why

* Current version is not compatible with vue 3

### Installation

```
import { createApp } from 'vue'
import App from './App.vue'
import router from './router'
import { StripePlugin } from 'vue-stripe'

const options = {
  pk: process.env.STRIPE_PUBLISHABLE_KEY,
  stripeAccount: process.env.STRIPE_ACCOUNT,
  apiVersion: process.env.API_VERSION,
  locale: process.env.LOCALE,
};


createApp(App).use(router).use(StripePlugin, options).mount('#app')
```

### Options API: Using this

```
<template>
// HTML here
</template>

<script>
export default {
 data () {
    return {
      token: null,
      cardNumber: null,
      cardExpiry: null,
      cardCvc: null,
    };
  },
 computed:  {
    stripeElements () {
      return this.$stripe.elements();
    },
  },
}
</script>
```

### Options API: Using inject

```
<template>
// HTML here
</template>

<script>
import { inject } from 'vue'

export default {
   mounted () {
       const stripe = inject('stripe')
   }
}
</script>
```

### Composition API

```
<template>
    // HTML here
</template>
<script>
import { ref, inject, computed, onMounted } from 'vue'

export default {
    setup() {
        const stripe = inject('stripe')
        const cardNumber = ref(null)
        const cardExpiry = ref(null)
        const cardCvc = ref(null)
        const style = reactive({
            base: {
                color: 'black',
            },
            invalid: {
                color: '#fa755a',
            },
        })

        const stripeElements = computed(() => {
            return stripe.elements()
        })

        const createToken = async () => {
            const { token, error } = await stripe.createToken(cardNumber.value);
            if (error) {
                // handle error here
                document.getElementById('card-error').innerHTML = error.message;
                return;
            }
            // handle the token
            // send it to your server
        }
        onMounted(() => {
            cardNumber.value = stripeElements.value.create('cardNumber', { style });
            cardNumber.value.mount('#card-number');
            cardExpiry.value = stripeElements.value.create('cardExpiry', { style });
            cardExpiry.value.mount('#card-expiry');
            cardCvc.value = stripeElements.value.create('cardCvc', { style });
            cardCvc.value.mount('#card-cvc');
        })

        return {
          createToken
       }
    }
}
</script>
```

## Notes

This may better fit under a v2 branch in order to keep the current version still compatible with vue 2

### CODE REVIEW

**Comment by timramseyjr** [comment]
I am new to vue3, but I am unable to access the stripe and element via ref in vue3 version. In the Vue 2 version I would do this to access them via this.$refs.elementRef

```
<stripe-element-card
              ref="elementRef"
              :pk="public_key"
          />
<button @click="confirmCardSetup">confirmCardSetup</button>


async confirmCardSetup() {
            const stripe = this.$refs.elementRef.stripe;
            const card = this.$refs.elementRef.element;
            const billingDetails = {
              name: this.user.name || this.user.email,
              email: this.user.email,
              phone: this.user.phone,
            };

            const resp = await stripe.createPaymentMethod({
              type: "card",
              card: card,
              billing_details: billingDetails,
            });
          }
```

When I try to do this with the vue3 version they are undefined

```
<template>
  <div>
    <stripe-element-card
        ref="cardElementRef"
        :pk="pk"
        @token="tokenCreated"
    />
    <button @click="getToken">getToken</button>
    <button @click="confirmCardSetup">confirmCardSetup</button>
  </div>
</template>
<script>
import { StripeElementCard } from 'vue-stripe3';
import { ref,onMounted } from 'vue';

export default {
  components: {
    StripeElementCard
  },
  setup() {
    const cardElementRef = ref(null)
    function tokenCreated(token){
      console.log(token);
    }
    function getToken(){
      this.cardElementRef.submit();
    }
   async function confirmCardSetup(){
      const stripe = this.cardElementRef.stripe;
      const cardElement = this.cardElementRef.element;
      console.log(stripe); //undefined
      console.log(cardElement);//undefined
    }
    return {
      tokenCreated,
      getToken,
      confirmCardSetup,
      cardElementRef
    }
  },
  props: {
    pk:String
  }
}
</script>
```

**Comment by gonzalojpv** [comment]
@timramseyjr :

Vue Stripe Plugin

## 1. Install The Plugin
```js
import { createApp } from 'vue'
import App from './App.vue'
import router from './router'
import { StripePlugin } from 'vue-stripe'

const options = {
  pk: process.env.STRIPE_PUBLISHABLE_KEY,
  stripeAccount: process.env.STRIPE_ACCOUNT,
  apiVersion: process.env.API_VERSION,
  locale: process.env.LOCALE,
};


createApp(App).use(router).use(StripePlugin, options).mount('#app')
```

## 2. Usages:
### Option API: ```this```
In the option api you can use ``this.$stripe`` to access the stripe

```js
<template>
// HTML here
</template>

<script>
export default {
 data () {
    return {
      token: null,
      cardNumber: null,
      cardExpiry: null,
      cardCvc: null,
    };
  },
 computed:  {
    stripeElements () {
      return this.$stripe.elements();
    },
  },
}
</script>
```
### Option API: ``inject``

```js
<template>
// HTML here
</template>

<script>
import { inject } from 'vue'

export default {
   mounted () {
       const stripe = inject('stripe')
   }
}
</script>
```
### Composition API ``inject``

```js
<template>
    // HTML here
</template>
<script>
import { ref, inject, computed, onMounted } from 'vue'

export default {
    setup() {
        const stripe = inject('stripe')
        const cardNumber = ref(null)
        const cardExpiry = ref(null)
        const cardCvc = ref(null)
        const style = reactive({
            base: {
                color: 'black',
                fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
                fontSmoothing: 'antialiased',
                fontSize: '14px',
                '::placeholder': {
                color: '#aab7c4',
                },
            },
            invalid: {
                color: '#fa755a',
                iconColor: '#fa755a',
            },
        })

        const stripeElements = computed(() => {
            return stripe.elements()
        })

        const createToken = async () => {
            const { token, error } = await stripe.createToken(cardNumber.value);
            if (error) {
                // handle error here
                document.getElementById('card-error').innerHTML = error.message;
                return;
            }

            console.log(token);
            // handle the token
            // send it to your server
        }
        onMounted(() => {
            cardNumber.value = stripeElements.value.create('cardNumber', { style });
            cardNumber.value.mount('#card-number');
            cardExpiry.value = stripeElements.value.create('cardExpiry', { style });
            cardExpiry.value.mount('#card-expiry');
            cardCvc.value = stripeElements.value.create('cardCvc', { style });
            cardCvc.value.mount('#card-cvc');
        })

        return {
          createToken
       }
    }
}
</script>
```

Screen Shot 2021-08-18 at 14 14 56

**Comment by timramseyjr** [comment]
@gonzalojpv I was trying to implement the `StripeElementCard` - https://vuestripe.com/stripe-elements/getting-started. Is that not carried over?

**Comment by gonzalojpv** [comment]
@timramseyjr  Yes, it was carried over, you just cannot use `this` on setup check the last comment `StripeElementCard`

**Comment by timramseyjr** [comment]
@gonzalojpv Thanks for pointing the this issue out. My example is talking about referencing the underlying element/stripe. I think they are not being returned in Card.vue, so that might be the issue, but I am very new to vue3

Should Card.vue be changed from
```
return {
      submit,
      modifiedSlot,
      onSubmit,
    };
```
to
```
return {
      submit,
      modifiedSlot,
      onSubmit,
      stripe,
      element
    };
```

**Comment by timramseyjr** [comment]
@gonzalojpv That was the issue. If you return stripe and element in the Card setup, then you can access them via `elementRef.value.stripe` and `elementRef.value.element`

**Comment by gonzalojpv** [comment]
@timramseyjr got it, I will send this change, thx

**Comment by gonzalojpv** [comment]
@timramseyjr  I sent commit, https://github.com/vue-stripe/vue-stripe/pull/221/commits/000bba4a8566989a91e65528688e323066c7daaf  also return 
```js
return {
      submit,
      modifiedSlot,
      onSubmit,
      stripe,
      element,
      clear,
      destroy,
      focus,
      unmount,
      update,
    };
```

**Comment by jofftiquez** [comment]
Hi, unfortunately, the friction for this PR is too large for me to merge. I will close this for now, and I will find time to move your thread to the Discussions tab as you guys clearly created a workaround for this. Apologies again. Thank you.

**Pull request closed without merging**
